#!/bin/sh

infile=$(realpath "$1")

if [ "$2" = "test" ]; then
    ln -sf "$infile" /test/code_test.go
    cd /test/
    go test -mod vendor /test/code_test.go
else
    ln -sf "$infile" /tmp/code.go
    /usr/bin/go build -o /tmp/code /tmp/code.go
    cat - | /tmp/code
fi
